export const STARDEW_SPECIAL_ORDERS = {
  town: {
    Caroline: "Island Ingredients",
    Clint: "Cave Patrol",
    Demetrius: "Aquatic Overpopulation",
    Demetrius2: "Biome Balance",
    Emily: "Rock Rejuvenation",
    Evelyn: "Gifts for George",
    Gunther: "Fragments of the past",
    Gus: "Gus' Famous Omelet",
    Lewis: "Crop Order",
    Linus: "Community Cleanup",
    Pam: "The Strong Stuff",
    Pierre: "Pierre's Prime Produce",
    Robin: "Robin's Project",
    Robin2: "Robin's Resource Rush",
    Willy: "Juicy Bugs Wanted!",
    Willy2: "Tropical Fish",
    Wizard: "A Curious Substance",
    Wizard2: "Prismatic Jelly",
  },

  qi: {
    QiChallenge2: "Qi's Crop",
    QiChallenge3: "Let's Play A Game",
    QiChallenge4: "Four Precious Stones",
    QiChallenge5: "Qi's Hungry Challenge",
    QiChallenge6: "Qi's Cuisine",
    QiChallenge7: "Qi's Kindness",
    QiChallenge8: "Extended Family",
    QiChallenge9: "Danger In The Deep",
    QiChallenge10: "Skull Cavern Invasion",
    QiChallenge12: "Qi's Prismatic Grange",
  },
};
