export const STARDEW_PROFESSIONS = {
  farming: {
    0: "Rancher",
    1: "Tiller",
    2: "Coopmaster",
    3: "Shepherd",
    4: "Artisan",
    5: "Agriculturist",
  },
  fishing: {
    6: "Fisher",
    7: "Trapper",
    8: "Angler",
    9: "Pirate",
    10: "Mariner",
    11: "Luremaster",
  },
  foraging: {
    12: "Forester",
    13: "Gatherer",
    14: "Lumberjack",
    15: "Tapper",
    16: "Botanist",
    17: "Tracker",
  },
  mining: {
    18: "Miner",
    19: "Geologist",
    20: "Blacksmith",
    21: "Prospector",
    22: "Excavator",
    23: "Gemologist",
  },
  combat: {
    24: "Fighter",
    25: "Scout",
    26: "Brute",
    27: "Defender",
    28: "Acrobat",
    29: "Desperado",
  },
};
