interface MuseumItem {
  title: string;
}

export const STARDEW_ARTIFACTS: Record<string, MuseumItem> = {
  96: { title: "Dwarf Scroll I" },
  97: { title: "Dwarf Scroll II" },
  98: { title: "Dwarf Scroll III" },
  99: { title: "Dwarf Scroll IV" },
  100: { title: "Chipped Amphora" },
  101: { title: "Arrowhead" },
  103: { title: "Ancient Doll" },
  104: { title: "Elvish Jewelry" },
  105: { title: "Chewing Stick" },
  106: { title: "Ornamental Fan" },
  107: { title: "Dinosaur Egg" },
  108: { title: "Rare Disc" },
  109: { title: "Ancient Sword" },
  110: { title: "Rusty Spoon" },
  111: { title: "Rusty Spur" },
  112: { title: "Rusty Cog" },
  113: { title: "Chicken Statue" },
  114: { title: "Ancient Seed" },
  115: { title: "Prehistoric Tool" },
  116: { title: "Dried Starfish" },
  117: { title: "Anchor" },
  118: { title: "Glass Shards" },
  119: { title: "Bone Flute" },
  120: { title: "Prehistoric Handaxe" },
  121: { title: "Dwarvish Helm" },
  122: { title: "Dwarf Gadget" },
  123: { title: "Ancient Drum" },
  124: { title: "Golden Mask" },
  125: { title: "Golden Relic" },
  126: { title: "Strange Doll (green)" },
  127: { title: "Strange Doll (yellow)" },
  579: { title: "Prehistoric Scapula" },
  580: { title: "Prehistoric Tibia" },
  581: { title: "Prehistoric Skull" },
  582: { title: "Skeletal Hand" },
  583: { title: "Prehistoric Rib" },
  584: { title: "Prehistoric Vertebra" },
  585: { title: "Skeletal Tail" },
  586: { title: "Nautilus Fossil" },
  587: { title: "Amphibian Fossil" },
  588: { title: "Palm Fossil" },
  589: { title: "Trilobite" },
};

export const STARDEW_MINERALS: Record<string, MuseumItem> = {
  60: { title: "Emerald" },
  62: { title: "Aquamarine" },
  64: { title: "Ruby" },
  66: { title: "Amethyst" },
  68: { title: "Topaz" },
  70: { title: "Jade" },
  72: { title: "Diamond" },
  74: { title: "Prismatic Shard" },
  80: { title: "Quartz" },
  82: { title: "Fire Quartz" },
  84: { title: "Frozen Tear" },
  86: { title: "Earth Crystal" },
  538: { title: "Alamite" },
  539: { title: "Bixite" },
  540: { title: "Baryte" },
  541: { title: "Aerinite" },
  542: { title: "Calcite" },
  543: { title: "Dolomite" },
  544: { title: "Esperite" },
  545: { title: "Fluorapatite" },
  546: { title: "Geminite" },
  547: { title: "Helvite" },
  548: { title: "Jamborite" },
  549: { title: "Jagoite" },
  550: { title: "Kyanite" },
  551: { title: "Lunarite" },
  552: { title: "Malachite" },
  553: { title: "Neptunite" },
  554: { title: "Lemon Stone" },
  555: { title: "Nekoite" },
  556: { title: "Orpiment" },
  557: { title: "Petrified Slime" },
  558: { title: "Thunder Egg" },
  559: { title: "Pyrite" },
  560: { title: "Ocean Stone" },
  561: { title: "Ghost Crystal" },
  562: { title: "Tigerseye" },
  563: { title: "Jasper" },
  564: { title: "Opal" },
  565: { title: "Fire Opal" },
  566: { title: "Celestine" },
  567: { title: "Marble" },
  568: { title: "Sandstone" },
  569: { title: "Granite" },
  570: { title: "Basalt" },
  571: { title: "Limestone" },
  572: { title: "Soapstone" },
  573: { title: "Hematite" },
  574: { title: "Mudstone" },
  575: { title: "Obsidian" },
  576: { title: "Slate" },
  577: { title: "Fairy Stone" },
  578: { title: "Star Shards" },
};
