export const STARDEW_CRAFTING_RECIPES = [
  "Cherry Bomb",
  "Bomb",
  "Mega Bomb",
  "Explosive Ammo",
  "Staircase",
  "Gate",
  "Wood Fence",
  "Stone Fence",
  "Iron Fence",
  "Hardwood Fence",
  "Mayonnaise Machine",
  "Bee House",
  "Preserves Jar",
  "Cheese Press",
  "Loom",
  "Keg",
  "Oil Maker",
  "Cask",
  "Fish Smoker",
  "Dehydrator",
  "Sprinkler",
  "Quality Sprinkler",
  "Iridium Sprinkler",
  "Scarecrow",
  "Deluxe Scarecrow",
  "Tapper",
  "Heavy Tapper",
  "Basic Fertilizer",
  "Quality Fertilizer",
  "Deluxe Fertilizer",
  "Speed-Gro",
  "Deluxe Speed-Gro",
  "Hyper Speed-Gro",
  "Basic Retaining Soil",
  "Quality Retaining Soil",
  "Deluxe Retaining Soil",
  "Tree Fertilizer",
  "Tent Kit",
  "Cookout Kit",
  "Wild Seeds (Sp)",
  "Wild Seeds (Su)",
  "Wild Seeds (Fa)",
  "Wild Seeds (Wi)",
  "Ancient Seeds",
  "Grass Starter",
  "Blue Grass Starter",
  "Tea Sapling",
  "Fiber Seeds",
  "Mystic Tree Seed",
  "Wood Floor",
  "Rustic Plank Floor",
  "Straw Floor",
  "Weathered Floor",
  "Crystal Floor",
  "Stone Floor",
  "Stone Walkway Floor",
  "Brick Floor",
  "Wood Path",
  "Gravel Path",
  "Cobblestone Path",
  "Stepping Stone Path",
  "Crystal Path",
  "Spinner",
  "Trap Bobber",
  "Sonar Bobber",
  "Cork Bobber",
  "Quality Bobber",
  "Treasure Hunter",
  "Dressed Spinner",
  "Barbed Hook",
  "Magnet",
  "Bait",
  "Deluxe Bait",
  "Wild Bait",
  "Magic Bait",
  "Challenge Bait",
  "Crab Pot",
  "Sturdy Ring",
  "Warrior Ring",
  "Ring of Yoba",
  "Thorns Ring",
  "Glowstone Ring",
  "Iridium Band",
  "Field Snack",
  "Bug Steak",
  "Life Elixir",
  "Oil of Garlic",
  "Monster Musk",
  "Fairy Dust",
  "Warp Totem: Beach",
  "Warp Totem: Mountains",
  "Warp Totem: Farm",
  "Warp Totem: Desert",
  "Warp Totem: Island",
  "Rain Totem",
  "Treasure Totem",
  "Torch",
  "Campfire",
  "Wooden Brazier",
  "Stone Brazier",
  "Gold Brazier",
  "Carved Brazier",
  "Stump Brazier",
  "Barrel Brazier",
  "Skull Brazier",
  "Marble Brazier",
  "Wood Lamp-post",
  "Iron Lamp-post",
  "Jack-O-Lantern",
  "Tub o' Flowers",
  "Flute Block",
  "Drum Block",
  "Transmute (Fe)",
  "Transmute (Au)",
  "Charcoal Kiln",
  "Crystalarium",
  "Furnace",
  "Heavy Furnace",
  "Lightning Rod",
  "Solar Panel",
  "Recycling Machine",
  "Seed Maker",
  "Slime Incubator",
  "Ostrich Incubator",
  "Slime Egg-Press",
  "Worm Bin",
  "Deluxe Worm Bin",
  "Bone Mill",
  "Geode Crusher",
  "Mushroom Log",
  "Bait Maker",
  "Mini-Jukebox",
  "Mini-Obelisk",
  "Farm Computer",
  "Hopper",
  "Anvil",
  "Mini-Forge",
  "Wicked Statue",
  "Statue Of Blessings",
  "Statue Of The Dwarf King",
  "Chest",
  "Big Chest",
  "Stone Chest",
  "Big Stone Chest",
  "Wood Sign",
  "Stone Sign",
  "Dark Sign",
  "Text Sign",
  "Garden Pot",
];
