interface RelatableNpc {}

// TODO: Include heart-events
export const STARDEW_RELATABLE_NPCS: Record<string, RelatableNpc> = {
  Abigail: {},
  Alex: {},
  Elliott: {},
  Emily: {},
  Haley: {},
  Harvey: {},
  Leah: {},
  Maru: {},
  Penny: {},
  Sam: {},
  Sebastian: {},
  Shane: {},
  Caroline: {},
  Clint: {},
  Demetrius: {},
  Dwarf: {},
  Evelyn: {},
  George: {},
  Gus: {},
  Jas: {},
  Jodi: {},
  Kent: {},
  Krobus: {},
  Lewis: {},
  Linus: {},
  Marnie: {},
  Pam: {},
  Pierre: {},
  Robin: {},
  Sandy: {},
  Vincent: {},
  Willy: {},
  Wizard: {},
  Leo: {},
};
