export const STARDEW_CRAFTING_RECIPES = [
  "Cherry Bomb",
  "Bomb",
  "Mega Bomb",
  "Gate",
  "Wood Fence",
  "Stone Fence",
  "Iron Fence",
  "Hardwood Fence",
  "Sprinkler",
  "Quality Sprinkler",
  "Iridium Sprinkler",
  "Mayonnaise Machine",
  "Bee House",
  "Preserves Jar",
  "Cheese Press",
  "Loom",
  "Keg",
  "Oil Maker",
  "Cask",
  "Basic Fertilizer",
  "Quality Fertilizer",
  "Speed-Gro",
  "Deluxe Speed-Gro",
  "Basic Retaining Soil",
  "Quality Retaining Soil",
  "Wild Seeds (Sp)",
  "Wild Seeds (Su)",
  "Wild Seeds (Fa)",
  "Wild Seeds (Wi)",
  "Ancient Seeds",
  "Wood Floor",
  "Straw Floor",
  "Weathered Floor",
  "Crystal Floor",
  "Stone Floor",
  "Wood Path",
  "Gravel Path",
  "Cobblestone Path",
  "Stepping Stone Path",
  "Crystal Path",
  "Spinner",
  "Trap Bobber",
  "Cork Bobber",
  "Treasure Hunter",
  "Dressed Spinner",
  "Barbed Hook",
  "Magnet",
  "Bait",
  "Wild Bait",
  "Crab Pot",
  "Sturdy Ring",
  "Warrior Ring",
  "Ring of Yoba",
  "Iridium Band",
  "Field Snack",
  "Life Elixir",
  "Oil of Garlic",
  "Torch",
  "Campfire",
  "Wooden Brazier",
  "Stone Brazier",
  "Gold Brazier",
  "Carved Brazier",
  "Stump Brazier",
  "Barrel Brazier",
  "Skull Brazier",
  "Marble Brazier",
  "Wood Lamp-post",
  "Iron Lamp-post",
  "Jack-O-Lantern",
  "Chest",
  "Furnace",
  "Scarecrow",
  "Seed Maker",
  "Staircase",
  "Explosive Ammo",
  "Transmute (Fe)",
  "Transmute (Au)",
  "Crystalarium",
  "Charcoal Kiln",
  "Lightning Rod",
  "Recycling Machine",
  "Tapper",
  "Worm Bin",
  "Slime Egg-Press",
  "Slime Incubator",
  "Warp Totem: Beach",
  "Warp Totem: Mountains",
  "Warp Totem: Farm",
  "Rain Totem",
  "Tub o' Flowers",
  "Wicked Statue",
  "Flute Block",
  "Drum Block",
];
