export const STARDEW_CRAFTING_RECIPES = [
  "Cherry Bomb",
  "Bomb",
  "Mega Bomb",
  "Gate",
  "Wood Fence",
  "Stone Fence",
  "Iron Fence",
  "Hardwood Fence",
  "Sprinkler",
  "Quality Sprinkler",
  "Iridium Sprinkler",
  "Mayonnaise Machine",
  "Bee House",
  "Preserves Jar",
  "Cheese Press",
  "Loom",
  "Keg",
  "Oil Maker",
  "Cask",
  "Fish Smoker",
  "Dehydrator",
  "Basic Fertilizer",
  "Quality Fertilizer",
  "Deluxe Fertilizer",
  "Speed-Gro",
  "Deluxe Speed-Gro",
  "Hyper Speed-Gro",
  "Basic Retaining Soil",
  "Quality Retaining Soil",
  "Deluxe Retaining Soil",
  "Tree Fertilizer",
  "Wild Seeds (Sp)",
  "Wild Seeds (Su)",
  "Wild Seeds (Fa)",
  "Wild Seeds (Wi)",
  "Ancient Seeds",
  "Grass Starter",
  "Blue Grass Starter",
  "Tea Sapling",
  "Fiber Seeds",
  "Mystic Tree Seed",
  "Wood Floor",
  "Rustic Plank Floor",
  "Straw Floor",
  "Weathered Floor",
  "Crystal Floor",
  "Stone Floor",
  "Stone Walkway Floor",
  "Brick Floor",
  "Wood Path",
  "Gravel Path",
  "Cobblestone Path",
  "Stepping Stone Path",
  "Crystal Path",
  "Spinner",
  "Trap Bobber",
  "Sonar Bobber",
  "Cork Bobber",
  "Quality Bobber",
  "Treasure Hunter",
  "Dressed Spinner",
  "Barbed Hook",
  "Magnet",
  "Bait",
  "Deluxe Bait",
  "Wild Bait",
  "Magic Bait",
  "Challenge Bait",
  "Crab Pot",
  "Sturdy Ring",
  "Warrior Ring",
  "Ring of Yoba",
  "Thorns Ring",
  "Glowstone Ring",
  "Iridium Band",
  "Field Snack",
  "Life Elixir",
  "Oil of Garlic",
  "Torch",
  "Campfire",
  "Wooden Brazier",
  "Stone Brazier",
  "Gold Brazier",
  "Carved Brazier",
  "Stump Brazier",
  "Barrel Brazier",
  "Skull Brazier",
  "Marble Brazier",
  "Wood Lamp-post",
  "Iron Lamp-post",
  "Jack-O-Lantern",
  "Chest",
  "Furnace",
  "Scarecrow",
  "Seed Maker",
  "Staircase",
  "Explosive Ammo",
  "Transmute (Fe)",
  "Transmute (Au)",
  "Crystalarium",
  "Charcoal Kiln",
  "Lightning Rod",
  "Recycling Machine",
  "Tapper",
  "Worm Bin",
  "Slime Egg-Press",
  "Slime Incubator",
  "Warp Totem: Beach",
  "Warp Totem: Mountains",
  "Warp Totem: Farm",
  "Rain Totem",
  "Tub o' Flowers",
  "Wicked Statue",
  "Flute Block",
  "Drum Block",
  "Wood Sign",
  "Stone Sign",
  "Garden Pot",
  "Deluxe Scarecrow",
  "Mini-Jukebox",
  "Warp Totem: Desert",
  "Fairy Dust",
  "Bug Steak",
  "Dark Sign",
  "Stone Chest",
  "Monster Musk",
  "Mini-Obelisk",
  "Farm Computer",
  "Ostrich Incubator",
  "Geode Crusher",
  "Solar Panel",
  "Bone Mill",
  "Warp Totem: Island",
  "Heavy Tapper",
  "Hopper",
  "Cookout Kit",
  "Anvil",
  "Bait Maker",
  "Big Chest",
  "Big Stone Chest",
  "Deluxe Worm Bin",
  "Heavy Furnace",
  "Mini-Forge",
  "Mushroom Log",
  "Statue Of Blessings",
  "Statue Of The Dwarf King",
  "Tent Kit",
  "Text Sign",
  "Treasure Totem",
];
